services:
  auth:
    image: apigwsample/auth
    networks:
    - krakend
  product:
    image: apigwsample/product
    networks:
    - krakend
  krakend:
    image: krakend
    command: run --config /etc/krakend/krakend.json
    volumes:
    - ./krakend:/etc/krakend
    networks:
    - krakend
    ports:
    - 8080:8080

networks:
  krakend:
